controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    image_sensor_broadcaster:
      type: image_sensor_broadcaster/ImageSensorBroadcaster

image_sensor_broadcaster:
  ros__parameters:
    interface_names.height: image_sensor/height
    interface_names.width: image_sensor/width
    interface_names.encoding: image_sensor/encoding
    interface_names.is_bigendian: image_sensor/is_bigendian
    interface_names.step: image_sensor/step
    interface_names.data: image_sensor/data