controller_manager:
  ros__parameters:
    update_rate: 20
    image_sensor_broadcaster:
      type: "image_sensor_broadcaster/ImageSensorBroadcaster"

image_sensor_broadcaster:
  ros__parameters:
    sensor_name: "image_sensor"
    frame_id: "link1"
    encoding: "rgb8"
    height: 1
    width: 14
