controller_manager:
  ros__parameters:
    update_rate: 20
    battery_state_broadcaster:
      type: "battery_state_broadcaster/BatteryStateBroadcaster"

battery_state_broadcaster:
  ros__parameters:
    sensor_name: "battery_sensor"
    state_interfaces:
      - voltage
      - temperature
      - current
      - charge
      - capacity
      - percentage